### PR TITLE
Validate document body is valid json.

### LINKED ISSUE #97: Storing NSNumber "inifinity" value causes entire body to be dropped
The following unit test fails (add to `Tests/Tests/DatastoreCRUD.m` to run):

``` Objective-C
-(void)testNumberInfinity
{
    NSError *error;
    CDTMutableDocumentRevision *doc = [CDTMutableDocumentRevision revision];
    doc.body = [@{
                  @"hello": @"world",
                  @"infinity": @(INFINITY)
                  } mutableCopy];
    CDTDocumentRevision *ob = [self.datastore createDocumentFromRevision:doc error:&error];

    STAssertNil(error, @"Error creating document");
    STAssertNotNil(ob, @"CDTDocumentRevision object was nil");

    CDTDocumentRevision *check = [self.datastore getDocumentWithId:ob.docId error:&error];
    STAssertNil(error, @"Error creating document");
    STAssertNotNil(check, @"CDTDocumentRevision object was nil");
    STAssertTrue([check.docId isEqualToString:ob.docId],
                 @"docId Mismatch: %@ != %@", ob.docId, check.docId);
    STAssertTrue([check.revId isEqualToString:ob.revId],
                 @"revId Mismatch: %@ != %@", ob.revId, check.revId);

    // things start failing here
    STAssertTrue([check.body count] > 0,
                 @"check.body is empty");
    STAssertTrue([ob.body[@"hello"] isEqual:check.body[@"hello"]],
                 @"hello did not match: %@ != %@", ob.body[@"hello"], check.body[@"hello"]);
    STAssertTrue([ob.body[@"infinity"] isEqual:check.body[@"infinity"]],
                 @"infinity did not match: %@ != %@", ob.body[@"infinity"], check.body[@"infinity"]);
}
```

Also note that `ob` reports that all is fine.

### PR DESCRIPTION
**Pull request by rhyshort**
Validate document body contains only valid json values
before attempting to save.

BugzID: 42641

Fixes #97

reviewer @mikerhodes 
reviewer @tomblench

### CODE REVIEW

File: Classes/common/CDTDatastore.m [hunk 1]
```diff
@@ -396,6 +396,25 @@ - (BOOL)validateBodyDictionary:(NSDictionary *)body error:(NSError *__autoreleas
             return NO;
         }
     }
+    
+    //now to check if the body contains valid json data
+    if(![NSJSONSerialization isValidJSONObject:body]){
+        //body isn't valid json, set error
+        if (error){
+            NSInteger code = 400;
```
Comment (jimix) [inline Classes/common/CDTDatastore.m]: Shouldn't you use `kTDStatusBadRequest` if you must use 400, or perhaps `kTDStatusBadJSON` would be even better

File: Tests/Tests/DatastoreCRUD.m [hunk 2]
```diff
@@ -83,6 +83,25 @@ -(NSArray*)generateDocuments:(int)count
 
 #pragma mark - CREATE tests
 
+
+-(void) testDocumentWithInvalidJsonBody
+{
+    NSError * error;
+    CDTMutableDocumentRevision * revision = [CDTMutableDocumentRevision revision];
+    revision.body = @{@"infiity":@(INFINITY)};
```
Comment (jimix) [inline Tests/Tests/DatastoreCRUD.m]: NIT: spelling `s/infiity/infinity/`

File: Classes/common/CDTDatastore.m [hunk 3]
```diff
@@ -396,6 +396,25 @@ - (BOOL)validateBodyDictionary:(NSDictionary *)body error:(NSError *__autoreleas
...
+            NSString * reason = @"Body contains invalid json data.";
+            NSString *description = [NSString stringWithFormat:@"%li %@",
+                                     (long)code,
+                                     reason];
+            NSDictionary *userInfo = @{
+                                   NSLocalizedFailureReasonErrorKey : reason,
+                                   NSLocalizedDescriptionKey : description
+                                   };
+        *error = [NSError errorWithDomain:TDHTTPErrorDomain code:code userInfo:userInfo];
```
Comment (tomblench) [inline Classes/common/CDTDatastore.m]: Indenting wrong here

File: Classes/common/CDTDatastore.m [hunk 4]
```diff
@@ -396,6 +396,25 @@ - (BOOL)validateBodyDictionary:(NSDictionary *)body error:(NSError *__autoreleas
             return NO;
         }
     }
+    
+    //now to check if the body contains valid json data
+    if(![NSJSONSerialization isValidJSONObject:body]){
```
Comment (tomblench) [inline Classes/common/CDTDatastore.m]: Should this test go before the "fields contain underscores" check which is above?

Comment (rhyshort) [inline Classes/common/CDTDatastore.m]: I'm not sure, but I think the order is correct, because we are checking for keys which are invalid, before checking if the whole thing can be serialised

Comment (tomblench) [inline Classes/common/CDTDatastore.m]: OK guess it depends which you think is the most important error if it is both invalid json and contains keys with underscores.

Comment (rhyshort) [inline Classes/common/CDTDatastore.m]: hmmm I'm not sure, @mikerhodes do you have an opinion on this?

Comment (mikerhodes) [inline Classes/common/CDTDatastore.m]: Gut feeling is to validate the JSON first.

File: Tests/Tests/DatastoreCRUD.m [hunk 5]
```diff
@@ -83,6 +83,25 @@ -(NSArray*)generateDocuments:(int)count
...
+    CDTDocumentRevision * rev = [self.datastore createDocumentFromRevision:revision
+                                                                     error:&error];
+    
+    XCTAssertNil(rev,@"revision is not nil");
+    XCTAssertNotNil(error,@"Error should be set");
+    XCTAssertEqual(400,
+                   error.code,
+                   @"Error code should be 400, but was %ld",
+                   (long)error.code);
+}
```
Comment (mikerhodes) [inline Tests/Tests/DatastoreCRUD.m]: Test name is only sort of accurate. Be more specific, `testDocumentWithInfinityValue`. 

There are other ways the document could be invalid, we should probably test them (e.g., non serialisable object?)

Comment (rhyshort) [inline Tests/Tests/DatastoreCRUD.m]: Done in 60532f6

File: Classes/common/CDTDatastore.m (hunk 4 above)
Comment (rhyshort) [inline Classes/common/CDTDatastore.m]: Switched in 60532f6

**Comment by mikerhodes** [comment]
@jimix can you verify this fixes your problem?

File: Tests/Tests/DatastoreCRUD.m [hunk 6]
```diff
@@ -83,6 +83,41 @@ -(NSArray*)generateDocuments:(int)count
...
+    NSError * error;
+    CDTMutableDocumentRevision * revision = [CDTMutableDocumentRevision revision];
+    revision.body = @{@"infinity":@(INFINITY)};
+    
+    CDTDocumentRevision * rev = [self.datastore createDocumentFromRevision:revision
+                                                                     error:&error];
+    
+    XCTAssertNil(rev,@"revision is not nil");
+    XCTAssertNotNil(error,@"Error should be set");
+    XCTAssertEqual(400,
```
Comment (jimix) [inline Tests/Tests/DatastoreCRUD.m]: umm.. I see you made the error `kTDStatusBadJSON` above, but in my space it is:
```objc
    kTDStatusBadJSON = 493,
```
How does this test pass?

File: Tests/Tests/DatastoreCRUD.m [hunk 7]
```diff
@@ -83,6 +83,41 @@ -(NSArray*)generateDocuments:(int)count
...
+                   error.code,
+                   @"Error code should be 400, but was %ld",
```
Comment (jimix) [inline Tests/Tests/DatastoreCRUD.m]: you will want to whack the `400` here as well.

File: Tests/Tests/DatastoreCRUD.m (hunk 6 above)
Comment (rhyshort) [inline Tests/Tests/DatastoreCRUD.m]: 493 isn't a http status so it is mapped to 400. https://github.com/cloudant/CDTDatastore/blob/master/Classes/common/touchdb/TDStatus.m#L42

**Comment by jimix** [comment]
This patch solves the problem for `NAN` and `+/-INFINITY` however storing `DBL_MAX` or `DBL_MIN` will continue to cause no error and an empty body on recall.
Here is a diff that shows the issue:
```diff
diff --git a/Tests/Tests/DatastoreCRUD.m b/Tests/Tests/DatastoreCRUD.m
index bdc7db4..9399b90 100644
--- a/Tests/Tests/DatastoreCRUD.m
+++ b/Tests/Tests/DatastoreCRUD.m
@@ -88,11 +88,16 @@
 {
     NSError * error;
     CDTMutableDocumentRevision * revision = [CDTMutableDocumentRevision revision];
-    revision.body = @{@"infinity":@(INFINITY)};
+    revision.body = @{@"infinity":@(DBL_MAX)};
     
     CDTDocumentRevision * rev = [self.datastore createDocumentFromRevision:revision
                                                                      error:&error];
-    
+    if (rev) {
+        CDTDocumentRevision *checkRev = [self.datastore getDocumentWithId:rev.docId error:&error];
+        XCTAssertNotNil(checkRev, "readback failed");
+        XCTAssertGreaterThan([checkRev.body count], 0, "readback empty");
+    }
+
     XCTAssertNil(rev,@"revision is not nil");
     XCTAssertNotNil(error,@"Error should be set");
     XCTAssertEqual(400,
```

**Comment by rhyshort** [comment]
@jimix failing to deserialise valid values DBL_MAX and DBL_MIN would be a subject for a separate PR.

**Comment by jimix** [comment]
@rhyshort, I'd be interested in seeing that, could you point me to that line of code?

**Comment by jimix** [comment]
:+1: for `NaN` and `+/-INFINITY`
However, the body of issue #97 includes a discussion of `MAX/MIN_DBL` so either we can't close #97 or I file another issue.

**Comment by mikerhodes** [comment]
Let's merge this, then work on the *DBL issue. :+1:. We'll need to remove the "fixes" bit of the description before closing.
