### PR TITLE
Remove reference to conflict resolution coming soon.

### LINKED ISSUE #256: Incorrect documentation on CDTDatastore
The documentation on CDTDatastore mentions that conflict resolution is coming, however it has been present for a number of releases, the documentation [here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/CDTDatastore.h#L57-L62) needs to be updated to mention the conflicts API.

### PR DESCRIPTION
**Pull request by rhyshort**
Remove reference to conflict resolution coming soon, and replace
it with a reference the `CDTDatastore+Conflicts.h` for
conflict resoultion functions.

Fixes #256

### CODE REVIEW

File: CDTDatastore/CDTDatastore.h [hunk 1]
```diff
@@ -54,12 +54,8 @@ extern NSString * __nonnull const CDTDatastoreChangeNotification;
  * propagated, thereby resolving the conflicted document across the set of
  * peers.
  *
- * **WARNING:** conflict resolution is coming in the next
- * release, where we'll be adding methods to:
- *
- * - Get the IDs of all conflicted documents within the datastore.</li>
- * - Get a list of all current revisions for a given document, so they
- *     can be merged to resolve the conflict.</li>
+ * See CDTDatastore+Conflicts.h for functions to resolve Document conflicts caused by
```
Comment (brynh) [inline CDTDatastore/CDTDatastore.h]: I'm happy this fixes the issue mentioned, but I also notice the paragraph before this mentions `[CDTDatastore deleteDocumentWithId:rev:error:]`, which doesn't exist, so that paragraph should probably be corrected while we're here.

Comment (rhyshort) [inline CDTDatastore/CDTDatastore.h]: Good spot Bryn, I'll go fix

Comment (rhyshort) [inline CDTDatastore/CDTDatastore.h]: done in 393430e, I have a feeling this is going to open a can of worms, we should probably go check the doc for the rest of the project, I'm going to raise a ticket for this to be sure we get all the out of date doc references

**Comment by rhyshort** [comment]
@brynh Also removed second forward declare of `CDTDatastore` in 8664b57

**Comment by brynh** [comment]
+1

File: CDTDatastore/CDTDatastore.h (hunk 1 above)
Comment (brynh) [inline CDTDatastore/CDTDatastore.h]: You could be right 😞

File: CDTDatastore/CDTDatastore.h [hunk 2]
```diff
@@ -48,18 +47,12 @@ extern NSString * __nonnull const CDTDatastoreChangeNotification;
...
- * propagated, thereby resolving the conflicted document across the set of
- * peers.
- *
- * **WARNING:** conflict resolution is coming in the next
- * release, where we'll be adding methods to:
- *
- * - Get the IDs of all conflicted documents within the datastore.</li>
- * - Get a list of all current revisions for a given document, so they
- *     can be merged to resolve the conflict.</li>
+ * using the conflict resoultion APIs. When the datastore is next replicated with a remote
```
Comment (brynh) [inline CDTDatastore/CDTDatastore.h]: Typo `resoultion` -> `resolution`

**Comment by brynh** [comment]
+1 once typo is fixed
