### PR TITLE
372 cookie expiry

### LINKED ISSUE #372: Cookie interceptors should check for expiry
We can optimise the cookie interceptors by checking if the existing cookie has expired in the request interceptor. This can be done by storing the cookie expiry date and checking it for each request, and we can avoid having to replay a request we know will fail.

### PR DESCRIPTION
**Pull request by ricellis**
## What

Added preemptive re-authentication for session cookies.

## How

Added session expiry checks to cookie handling:
* Stored an array of `NSHTTPCookie` instead of just a string of one cookie value.
* Removed handling of `Set-Cookie` and `Cookie` headers in our code, use `NSMutableURLRequest` and `NSHTTPCookie` utilities instead.
* Disabled built-in cookie handling on `_session` and `_iam_session` requests.
* Added `hasValidCookieWithName` method to check for existence of a cookie with more than 5 minutes until expiry for the request URL.
* Added check for `Set-Cookie` header on responses to skip `_session` round trip where the server operates a sliding window.

## Testing

* Added tests for preemptive renewal for _session and _iam_session.
* Added test for Set-Cookie header on a non-session response.
* Shared OHHTTPStubsHelper between both session tests.
 * Corrected cookie name in `CDTIAMSessionCookieInterceptorTests`.
* Stopped tests crashing when more requests were made than mock stubs (fail with 555 instead). * Refactored `_session` success test to also use stub requests.
* Refactored test assertions for new code and to check Cookie headers where possible and removed TODOs.
* Added Max-Age to mock cookies

## Issues

Fixes #372

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://github.com/cloudant/CDTDatastore/blob/master/DCO1.1.txt)
- [x] You have added tests for any code changes
- [x] You have updated the [CHANGELOG.md](https://github.com/cloudant/CDTDatastore/blob/master/CHANGELOG.md)
- [x] You have completed the PR template below:

### CODE REVIEW

File: CDTDatastoreTests/CDTIAMSessionCookieInterceptorTests.m [hunk 1]
```diff
@@ -45,54 +46,6 @@ @interface CDTIAMSessionCookieInterceptor ()
 static const NSString *testCookieHeaderValue2 =
 @"IAMSession=dG9tYmxlbmNoOjU5NTM0QzgyOhqHa60IlqPmGR8vTVIK-tzhopMR";
 
-// helper to sequence a number of stubbed responses
-
-@interface OHHTTPStubsHelper : NSObject
```
Comment (emlaver) [inline CDTDatastoreTests/CDTIAMSessionCookieInterceptorTests.m]: +1 for moving this into its own header and implementation file.

Comment (ricellis) [inline CDTDatastoreTests/CDTIAMSessionCookieInterceptorTests.m]: I guess it will also be helpful for your `403` test cases in issue #371

File: CDTDatastoreTests/CDTSessionCookieInterceptorTests.m [hunk 2]
```diff
@@ -39,6 +47,11 @@ @implementation CDTSessionCookieInterceptorTests
 
 - (void)setUp
 {
+    setenv("CDT_TEST_ENABLE_OHHTTPSTUBS", "1", true);
```
Comment (tomblench) [inline CDTDatastoreTests/CDTSessionCookieInterceptorTests.m]: Should unset this in the teardown, otherwise the background session won't be used for all network requests after these tests. It's not a big deal but our tests should be as close to production usage as possible.

File: CDTDatastoreTests/OHHTTPStubsHelper.h [hunk 3]
```diff
@@ -0,0 +1,26 @@
+//
+//  OHHTTPStubsHelper.h
+//
+//  Copyright © 2017 IBMCloudant. All rights reserved.
```
Comment (tomblench) [inline CDTDatastoreTests/OHHTTPStubsHelper.h]: Should this just be "IBM Corporation"?

File: CDTDatastoreTests/OHHTTPStubsHelper.m [hunk 4]
```diff
@@ -0,0 +1,53 @@
+//
+//  OHHTTPStubsHelper.m
+//
+//  Copyright © 2017 IBMCloudant. All rights reserved.
```
Comment (tomblench) [inline CDTDatastoreTests/OHHTTPStubsHelper.m]: As above

File: CDTDatastoreTests/CDTSessionCookieInterceptorTests.m (hunk 2 above)
Comment (ricellis) [inline CDTDatastoreTests/CDTSessionCookieInterceptorTests.m]: Fixed in 90495c44fd2852d4433dfa7bf289a737a427ae16

File: CDTDatastoreTests/OHHTTPStubsHelper.h (hunk 3 above)
Comment (ricellis) [inline CDTDatastoreTests/OHHTTPStubsHelper.h]: Haha yes, I guess I got distracted when I was updating that and helpfully copied it to the other file as well.
Fixed in 37f94a91ef9b9dc0136f4c84411d18e28baa2805

File: CDTDatastoreTests/OHHTTPStubsHelper.m (hunk 4 above)
Comment (ricellis) [inline CDTDatastoreTests/OHHTTPStubsHelper.m]: Fixed in 37f94a91ef9b9dc0136f4c84411d18e28baa2805
