### PR TITLE
Make Replication a one liner.

### LINKED ISSUE #268: Make Replication a one liner
The aim here is to go from:

```objc
CDTReplicator *replicator = [datastore pushReplicationTarget:remoteDatabaseURL 
                                                withDelegate:self
                                                       error:&error];
[replicator start];
```
to this:

```
[datastore pushReplicationTarget: remoteDatabaseURL completionBlock: ...];
```

The work here is therefore to work out how:

- to call replicator.start from the pushReplicationTarget:completionBlock: method.
- the arguments to the callback (at least some status and error, like CloudKit).
- to encapsulate a delegate which calls the callback.

### PR DESCRIPTION
**Pull request by rhyshort**
## What
Make replication a one liner.

## How
- Added new methods to CDTDatastore+Replication to make replication easier to set up.
    - Objc looks like :
```objc
[self.datastore pushReplicationWithTarget:remoteURL completionHandler:^(NSError *error) {
        // do something
    }];

[self.datastore pullReplicationWithSource:remoteURL completionHandler:^(NSError *error) {
        // do something
    }];
```
   - Swift looks like:
```swift
self.datastore.push(to: remote) { error in 
    // do something
}
self.datastore.pull(from: remote) { error in 
    // do something
 }
```
- Added CDTDatastore+Replication to CloudantSync.h

## Testing

Two new tests have been added to ReplicationAcceptance since they require a remote database.
The tests are hardcoded to use 10 documents as this is likely to complete within the
timeout for the expectation.

## Issues

Resolves #268

## Notes

This change requires Xcode 8.

### CODE REVIEW

**Comment by xpqz** [comment]
The semantics look lovely, Rhys.

File: CDTDatastoreReplicationAcceptanceTests/ReplicationAcceptance.m [hunk 1]
```diff
@@ -13,6 +13,7 @@
 #import <CDTDatastore/CloudantSync.h>
 #import <CDTDatastore/CloudantSyncEncryption.h>
 
+
```
Comment (emlaver) [inline CDTDatastoreReplicationAcceptanceTests/ReplicationAcceptance.m]: You can remove this extra space.

**Comment by emlaver** [comment]
This looks good to me +1
