### PR TITLE
Fix warnings

### LINKED ISSUE #329: CDTDatastore 1.1.1 warnings for Swift Project
A new Swift iOS app using CDTDatastore 1.1.1 from CocoaPods produces the following errors:

```

CDTDatastore/CDTDatastore/Encryption/CDTEncryptionKey.h:37:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'

CDTDatastore/CDTDatastore/Encryption/CDTEncryptionKeySimpleProvider.h:32:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'

CDTDatastore/CDTDatastore/HTTP/CDTURLSessionTask.h:42:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
```

### PR DESCRIPTION
**Pull request by rhyshort**
## What

Fix warnings for nullability, pointer mismatch and double variable assignment.
## How
- Correct nullability annotations for `init` methods and use `NSAssert` to stop users calling the method dynamically in debug builds.
- Remove second assignment of `success`
- Correct the parameter types for `setState:forKey:`
## Testing
- No new tests
##  Issues

Fixes #329

### CODE REVIEW

File: CDTDatastore/Encryption/CDTEncryptionKey.h [hunk 1]
```diff
@@ -27,14 +27,15 @@
 // Size (bytes) of the DPK (Data Protection Key)
 #define CDTENCRYPTIONKEY_KEYSIZE 32
 
+NS_ASSUME_NONNULL_BEGIN
```
Comment (ricellis) [inline CDTDatastore/Encryption/CDTEncryptionKey.h]: I'm confused what value this is providing here, with this in place shouldn't we remove:
* the `nonnull` from the attribute list on line 36
* the `nonnull` annotations from `NSData *` on lines 47 and 51
* the `nonnull` from `CDTEncryptionKey *` on line 49

File: CDTDatastore/Encryption/CDTEncryptionKeySimpleProvider.h [hunk 2]
```diff
@@ -27,12 +27,14 @@
  @see CDTEncryptionKeyProvider
  @see CDTEncryptionKey
  */
+NS_ASSUME_NONNULL_BEGIN
```
Comment (ricellis) [inline CDTDatastore/Encryption/CDTEncryptionKeySimpleProvider.h]: Again I think this audited region allows us to remove `nonnull` from `NSData *` on lines 35, 37

File: CDTDatastore/HTTP/CDTURLSessionTask.m [hunk 3]
```diff
@@ -57,7 +57,7 @@ @interface CDTURLSessionTask ()
 
 @implementation CDTURLSessionTask
 
-- (nullable instancetype)init
+- (instancetype)init
```
Comment (ricellis) [inline CDTDatastore/HTTP/CDTURLSessionTask.m]: So this isn't `nullable` because it is always `nil`, rather than possibly being `nil`?

File: CDTDatastore/Encryption/CDTEncryptionKeySimpleProvider.h (hunk 2 above)
Comment (rhyshort) [inline CDTDatastore/Encryption/CDTEncryptionKeySimpleProvider.h]: done in 36291e5

**Comment by ricellis** [comment]
Copyrights need updating

**Comment by rhyshort** [comment]
@ricellis done.
