### PR TITLE
352 fix queries with both $not and $size operators

### LINKED ISSUE #352: [help] query structure for find.
Hi, is the code a right query structure ? because when I tried it I got an error message.
"articles" is an array in "datastoreTopics" I want to get all the "topics" that have more than one article.

Code:
NSDictionary *query = @{@"articles" : @{@"$not" : @{@"$size":@1}} };
CDTQResultSet *result = [datastoreTopics find:query
									skip:_pageIndex
									limit:_pageSize
									fields:fields
									sort:sortDocument];
Error : 
DB Error: 1 "near "?": syntax error"
DB Query: SELECT _id FROM "_t_cloudant_sync_query_index_basic" WHERE _id NOT IN (SELECT _id FROM "_t_cloudant_sync_query_index_basic" WHERE "articles" (null) ?);

### PR DESCRIPTION
**Pull request by emlaver**
*What* 
Fix bug for handling queries like `{ "$not" : { "$size" : 1} }`. 

*How*
- Added recursion logic to handle size operator in negated clause

*Testing*
- Added tests to CDTQQueryExecutorTests and CDTQQuerySqlTranslatorTests

fixes #352

### CODE REVIEW

File: CDTDatastore/query/CDTQQuerySqlTranslator.m [hunk 1]
```diff
@@ -315,6 +315,8 @@ + (BOOL)isOperator:(NSString *)operator inClause:(NSArray *)clause
             if (predicate[operator]) {
                 found = YES;
                 break;
+            } else if ([predicate isKindOfClass:[NSDictionary class]]) {
+                [self isOperator:operator inClause:[NSArray arrayWithObjects:predicate, nil]];
```
Comment (emlaver) [inline CDTDatastore/query/CDTQQuerySqlTranslator.m]: Remove in b71cbf6.

File: CDTDatastoreTests/CDTQQueryExecutorTests.m [hunk 2]
```diff
@@ -1125,6 +1125,14 @@
                 expect(result.documentIds.count).to.equal(5);
             });
             
+            it(@"works with $size operator", ^{
```
Comment (emlaver) [inline CDTDatastoreTests/CDTQQueryExecutorTests.m]: Removed this test.  Added more appropriate tests in 5a1b432.

File: CDTDatastore/query/CDTQQuerySqlTranslator.m [hunk 3]
```diff
@@ -457,6 +457,12 @@ + (CDTQSqlParts *)wherePartsForAndClause:(NSArray *)clause usingIndex:(NSString
                     placeholder = [NSString stringWithFormat:@"? %@ ?", operatorMap[EQ]];
                     [sqlParameters addObject:modulus[0]];
                     [sqlParameters addObject:modulus[1]];
+                } else if ([operator isEqualToString:SIZE]) {
```
Comment (emlaver) [inline CDTDatastore/query/CDTQQuerySqlTranslator.m]: Removed in 5a1b432.

File: CDTDatastoreTests/CDTQQueryExecutorTests.m [hunk 4]
```diff
@@ -1880,6 +1886,33 @@
...
         });
         
+        it(@"correctly returns a result set when argument is negative in negated clause", ^{
+            NSDictionary* query = @{ @"pet": @{ @"$not" : @{ @"$size": @-1 }} };
+            CDTQResultSet* result = [im find:query];
+            expect(result).toNot.beNil();
+            expect(result.documentIds.count).to.equal(8);
+        });
+        
+        it(@"correctly returns empty result set when argument is not a whole number in negated clause", ^{
```
Comment (brynh) [inline CDTDatastoreTests/CDTQQueryExecutorTests.m]: `empty` -> `a`
