### PR TITLE
269 datastore documentation

### LINKED ISSUE #269: Documentation issue regarding deleted datastores
The documentation for CDTDatastoreManager -deleteDatastoreNamed:error: says 

"it is the responsibility of the caller to ensure that extensions should be shutdown (and their underlying databases closed) before calling this method."

However, a CDTDatastore -close does not exist nor is there any documentation on what an extension is and how to shut it down.

### PR DESCRIPTION
**Pull request by rhyshort**
# What
1) Make sure databases are closed in the index manager.
2) Correct documentation of CDTDatastoreManager

## How
1) call `[database close]` in dealloc and before returning `nil` when opening the database failed because migrations couldn't be completed. 
2) Correct documentation of CDTDatastoreManager by removing incorrect doc comment.

## Issues

Fixes #269

### CODE REVIEW

File: CDTDatastore/CDTDatastoreManager.h [hunk 1]
```diff
@@ -55,9 +55,6 @@ extern NSString *__nonnull const CDTDatastoreErrorDomain;
 
  All datastore files, including attachments and extensions, are deleted.
```
Comment (emlaver) [inline CDTDatastore/CDTDatastoreManager.h]: Should we mention that `[database close]` is now being called? Or, would it be enough in the CHANGELOG.md?

Comment (rhyshort) [inline CDTDatastore/CDTDatastoreManager.h]: I think it's something for the change log. Since there is no way to explicitly  close the index manager, you just let it deallocate and clean it's self up.

**Comment by emlaver** [comment]
LGTM +1
